### ISSUE TITLE
Any thoughts on injected store w/ correct owner/container?

### ISSUE THREAD

**Issue by snewcomer** [toranb/ember-2-skeleton-app#1]
https://github.com/toranb/ember-2-skeleton-app/blob/master/tests/unit/user-deserializer-test.js#L16

Can't seem to get around the `"Assertion Failed: Attempting to lookup an injected property on an object without a container, ensure that the object was instantiated via a container."` when upgrading past Ember-Cli 1.13.4.  It looks like this works b/c the store is explicitly passed to the object, whereas I need to look it up on the object when the test is ran.  Looked at your simple store dummy app/tests as well and used the owner polyfill to register the simple store service, but still have the same problem.

**Comment by toranb** [comment]
I found this problem upgrading from ember-cli 1.13.13 this weekend myself. I'll give it a more in-depth look between now and EmberConf as I use this helper as part of the curriculum

**Comment by toranb** [comment]
My ember-conf curriculum is stuck w/ simple-store 3.5 from the looks of it so I'll need to get back to this at the end of the month (sorry for the delay)

**Comment by toranb** [comment]
@snewcomer I finally got around to looking at this broken unit test and it ended up fairly simple

https://github.com/toranb/ember-2-skeleton-app/commit/3513d23b455d0233f8a154aa1b29e33dc2c771a4

If you are using v4.x and have deserializers like this try to swap the name from `store` to `simpleStore` in the create as you see above. Report back to let me know how the upgrade to ember v2.4.5 goes

**Comment by snewcomer** [comment]
@toranb So the problem I am having the DI object (the service) available in unit tests when the object (User model) is not accessed through the container nor is explicitly given the store as you did in the commit above.  See below for two tests that show this...First test fails and the second one (with the DI object passed to the User model instance) passes.  Any thoughts?

https://github.com/snewcomer/ember-2-skeleton-app/commit/cd730be476f89b0910d4b8a6d3c30d82ba104491

**Comment by snewcomer** [comment]
I see you use the getOwner function in your simple store, which would require the `moduleFor` qunit module.  I wonder if this is a potential sol'n???


https://github.com/toranb/ember-cli-simple-store/blob/3dd29d5b01c864a98e0e22da2524bb974aaf2cde/tests/unit/relationship-test.js#L11

**Comment by toranb** [comment]
Ah, simple fix after all :)

In the registration helper just remove 'store:main' and add 'service:simpleStore' in it's place

https://github.com/toranb/ember-2-skeleton-app/commit/25a5b29cbf963a76d2093df31375da12dfb7792a

**Comment by snewcomer** [comment]
@toranb main problem is still this, which I think makes sense because the store instance which has the simpleStore service injected into it was not accessed through the container but from a store.pus.  Still debugging and trying to get a failing test here.

"Assertion Failed: Attempting to lookup an injected property on an object without a container, ensure that the object was instantiated via a container."

**Comment by snewcomer** [comment]
@toranb so I've paired it down to the same test setup (registration) with the same assertion, with the same test helper file and the same model, but still getting the DI injection error above.  

The main difference is that this work is in the add on dummy app.  That is all I can think of now.

**Comment by snewcomer** [comment]
I'll spin up an add on with deps to see what happens and push up in ~30min

**Comment by snewcomer** [comment]
@toranb here is the project with the failing dummy app test if you don't mind taking a look at it.

https://github.com/snewcomer/watter

**Comment by toranb** [comment]
fixed :) funny hack but it seems to solve the issue

https://github.com/snewcomer/watter/pull/1
